version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    machine: true
    steps:
    - checkout
    - node/install-node:
        version: 14.12.0
    - node/install-yarn:
        version: 1.22.10
    - node/with-cache:
        steps:
        - run:
            name: Install dependencies
            command: yarn install
        cache-key: package.json
        use-strict-cache: true
    - run:
        name: Run tests
        command: yarn test

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
                only:
                  - main